name: Update Readme Template

on: 
    schedule:
        - cron: '0 0 0 * * ?' # todo dia a meia noite
    push: 
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.TOKEN }}
        message: 'update readme github actions'