name: Update Readme Template

on: 
    schedule:
        # - cron: '0 0 * * *' # todo dia a meia noite
        -cron: '*/5 * * * *'
    push: 
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.TOKEN }}
        message: 'update readme github actions'