name: Update Readme Template

on: 
    schedule:
        - cron: '*/5 * * * *'
    push: 
        branches: [ master ]

jobs:
  publish:
    name: Publish Readme.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
            fetch-depth: 0

      - name: Generate Readme
        with:
            token: ${{ secrets.my_token }}
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name "GitHub Action"
            git config user.email "action@github.com"
            git add .
            git commit -m "Auto-update README.md"
            git push
          fi